apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud
  namespace: lux-cloud
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  labels:
    app.kubernetes.io/part-of: lux-cloud
spec:
  ingressClassName: ingress
  rules:
  - host: lux.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend: { service: { name: cloud, port: { number: 80 } } }
  - host: www.lux.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend: { service: { name: cloud, port: { number: 80 } } }
  tls:
  - hosts: [lux.cloud, www.lux.cloud]
    secretName: cloud-lux-tls
